DAC_VAR_WEIGHT = 0.2

DAC_MAX_SIMILARITY = 20
DAC_MIN_SIMILARITY = 0

DAC2_MAX_SIMILARITY = 20
DAC2_MIN_SIMILARITY = 0

CIFAR10_NUM_CLASSES = 10
CIFAR100_NUM_CLASSES = 100
FASHIONMNIST_NUM_CLASSES = 10
SVHN_NUM_CLASSES = 10
MNIST_NUM_CLASSES = 10
PACS_NUM_CLASSES = 7

NUM_ROUNDS_BETWEEN_TESTS = 5
NUM_ROUNDS_WITH_CLUSTER_TESTS = 15
TEST_BATCHSIZE = 128

TEST_NUM_DATAPOINTS = 500 # Used for client validation on test set
TEST_PACS_NUM_DATAPOINTS = 250

ENABLE_PIN_MEMORY = True   # Got a slightly speed improvement ~5% on mnist, +-1% on synthetic
WORKER_SIZE = 0

MIN_LOSS = 10**(-10)

EARLY_STOPPING_PATIENCE = 50